/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Calendar: typeof import('./src/components/ui/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./src/components/ui/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./src/components/ui/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./src/components/ui/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./src/components/ui/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./src/components/ui/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./src/components/ui/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./src/components/ui/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./src/components/ui/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./src/components/ui/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./src/components/ui/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./src/components/ui/calendar/CalendarPrevButton.vue')['default']
    ChangeLanguageDropdownButton: typeof import('./src/components/button/ChangeLanguageDropdownButton.vue')['default']
    ChangeThemeDropdownButton: typeof import('./src/components/button/ChangeThemeDropdownButton.vue')['default']
    DatePicker: typeof import('./src/components/date-picker/DatePicker.vue')['default']
    DatePickerDisplayCard: typeof import('./src/components/card/DatePickerDisplayCard.vue')['default']
    DevelopProgressCard: typeof import('./src/components/card/DevelopProgressCard.vue')['default']
    DevelopProgressDiagram: typeof import('./src/components/diagram/DevelopProgressDiagram.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FooterBar: typeof import('./src/components/layout/FooterBar.vue')['default']
    NativeSelect: typeof import('./src/components/ui/native-select/NativeSelect.vue')['default']
    NativeSelectOptGroup: typeof import('./src/components/ui/native-select/NativeSelectOptGroup.vue')['default']
    NativeSelectOption: typeof import('./src/components/ui/native-select/NativeSelectOption.vue')['default']
    NavBar: typeof import('./src/components/menu/NavBar.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverAnchor: typeof import('./src/components/ui/popover/PopoverAnchor.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AnimatePresence: typeof import('motion-v')['AnimatePresence']
  const Button: typeof import('./src/components/ui/button/Button.vue')['default']
  const Calendar: typeof import('./src/components/ui/calendar/Calendar.vue')['default']
  const CalendarCell: typeof import('./src/components/ui/calendar/CalendarCell.vue')['default']
  const CalendarCellTrigger: typeof import('./src/components/ui/calendar/CalendarCellTrigger.vue')['default']
  const CalendarGrid: typeof import('./src/components/ui/calendar/CalendarGrid.vue')['default']
  const CalendarGridBody: typeof import('./src/components/ui/calendar/CalendarGridBody.vue')['default']
  const CalendarGridHead: typeof import('./src/components/ui/calendar/CalendarGridHead.vue')['default']
  const CalendarGridRow: typeof import('./src/components/ui/calendar/CalendarGridRow.vue')['default']
  const CalendarHeadCell: typeof import('./src/components/ui/calendar/CalendarHeadCell.vue')['default']
  const CalendarHeader: typeof import('./src/components/ui/calendar/CalendarHeader.vue')['default']
  const CalendarHeading: typeof import('./src/components/ui/calendar/CalendarHeading.vue')['default']
  const CalendarNextButton: typeof import('./src/components/ui/calendar/CalendarNextButton.vue')['default']
  const CalendarPrevButton: typeof import('./src/components/ui/calendar/CalendarPrevButton.vue')['default']
  const ChangeLanguageDropdownButton: typeof import('./src/components/button/ChangeLanguageDropdownButton.vue')['default']
  const ChangeThemeDropdownButton: typeof import('./src/components/button/ChangeThemeDropdownButton.vue')['default']
  const DatePicker: typeof import('./src/components/date-picker/DatePicker.vue')['default']
  const DatePickerDisplayCard: typeof import('./src/components/card/DatePickerDisplayCard.vue')['default']
  const DevelopProgressCard: typeof import('./src/components/card/DevelopProgressCard.vue')['default']
  const DevelopProgressDiagram: typeof import('./src/components/diagram/DevelopProgressDiagram.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const FooterBar: typeof import('./src/components/layout/FooterBar.vue')['default']
  const NativeSelect: typeof import('./src/components/ui/native-select/NativeSelect.vue')['default']
  const NativeSelectOptGroup: typeof import('./src/components/ui/native-select/NativeSelectOptGroup.vue')['default']
  const NativeSelectOption: typeof import('./src/components/ui/native-select/NativeSelectOption.vue')['default']
  const NavBar: typeof import('./src/components/menu/NavBar.vue')['default']
  const Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
  const PopoverAnchor: typeof import('./src/components/ui/popover/PopoverAnchor.vue')['default']
  const PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
  const PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}